version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./aaa:/usr/share/nginx/aaa
      - ./bbb:/usr/share/nginx/bbb
      - ./nginx.conf:/etc/nginx/conf.d/default.conf